# Speed

# list

In [1]:
a = [i for i in range(10000000)]

b = [i for i in range(10000000,20000000)]

c =[]

import time

Start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])

print(time.time() - Start)

1.6309690475463867


Checking time with **Numpy**

In [2]:
import numpy as np

a = np.arange(10000000)

b = np.arange(10000000,20000000)

start = time.time()
c = a + b

print(time.time() - start)

0.16305923461914062


# Memory

In [1]:
a = [i for i in range(10000000)]

import sys
print(sys.getsizeof(a))


89095160


Checking in numpy

In [4]:
import numpy as np
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

Convenience

# Advance indexing



In [5]:
a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
#Fancy indexing
#Fetch 1,3,4 rows

print(a[[0,2,3]])

[[ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
b = np.arange(24).reshape(6,4)
print(b)

print('------------------------------Fetch rows')
#Fetch the 1,3,4,6 rows

print(b[[0,2,3,5]])

print('------------------------------Fetch column')

print(b[:,[0,2,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
------------------------------Fetch rows
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]]
------------------------------Fetch column
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]
