#To check numpy is install are not ?

In [1]:
pip show numpy


Note: you may need to restart the kernel to use updated packages.


To install the numpy

In [2]:
!pip install numpy


   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.5 MB 3.0 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.5 MB 3.5 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.5 MB 3.4 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.5 MB 3.8 MB/s eta 0:00:03
   ---------------- ----------------------- 5.0/12.5 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.5 MB 4.8 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.5 MB 5.5 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.5 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 5.4 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!python -m pip install --upgrade pip


   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------- ----------- 1.3/1.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 1.7 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1


In [4]:
!pip install numpy


Check the numpy version


In [5]:
import numpy as np
print(np.__version__)

2.4.6


1D Array


In [6]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


2D Array

In [14]:
arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


3D Array

In [16]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


np.Zer0  --> Store with Tuples ()

In [23]:
z = np.zeros((2, 2))
print(z)


[[0. 0.]
 [0. 0.]]


Ones

In [24]:
O = np.ones((2,3))
print(O)

[[1. 1. 1.]
 [1. 1. 1.]]


Full display with Same number


In [25]:
print(np.full((2,3),9))


[[9 9 9]
 [9 9 9]]


dtype : return the datatype

In [29]:
types =  np.array([1,2,3,4],dtype=float)
print(types)

[1. 2. 3. 4.]


Arange : to iteration

In [30]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


below every second numper was skilled because in parameter we uesd (startwith, endwith, skip or stepup)


In [31]:
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]
