#To check numpy is install are not ?

In [1]:
pip show numpy


Note: you may need to restart the kernel to use updated packages.


To install the numpy

In [2]:
!pip install numpy


   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.5 MB 3.0 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.5 MB 3.5 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.5 MB 3.4 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.5 MB 3.8 MB/s eta 0:00:03
   ---------------- ----------------------- 5.0/12.5 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.5 MB 4.8 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.5 MB 5.5 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.5 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 5.4 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!python -m pip install --upgrade pip


   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------- ----------- 1.3/1.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 1.7 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1


In [4]:
!pip install numpy


Check the numpy version


In [5]:
import numpy as np
print(np.__version__)

2.4.6


1D Array


In [6]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


2D Array

In [14]:
arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


3D Array

In [16]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


np.Zer0  --> Store with Tuples ()

In [23]:
z = np.zeros((2, 2))
print(z)


[[0. 0.]
 [0. 0.]]


Ones

In [24]:
O = np.ones((2,3))
print(O)

[[1. 1. 1.]
 [1. 1. 1.]]


Full display with Same number


In [25]:
print(np.full((2,3),9))


[[9 9 9]
 [9 9 9]]


dtype : return the datatype

In [29]:
types =  np.array([1,2,3,4],dtype=float)
print(types)

[1. 2. 3. 4.]


Arange : to iteration

In [30]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


below every second numper was skilled because in parameter we uesd (startwith, endwith, skip or stepup)


In [31]:
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


Reshape()

In [18]:

b = np.arange(1,15).reshape(7,2)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


To generate random numbers between 0 and 1 in NumPy, you can use **np.random.rand()**. By default, the datatype is float.

In [20]:

np.random.randn(3,4)

array([[ 1.69263501, -1.64391328, -0.99981107, -0.79885929],
       [-0.57374777,  2.95136335, -2.249469  ,  0.59904486],
       [-1.66651292, -0.85971196, -0.02029651,  2.03602175]])

np.linspace (note the spelling: linspace, not "linespace") is a NumPy function that generates a sequence of evenly spaced numbers over a specified interval.

numpy.linspace(start, stop, num=50, endpoint=True, dtype=None)


In [21]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

**identity**()

_np.identity is a NumPy function that creates an identity matrix — a square matrix with ones on the main diagonal and zeros elsewhere._

Syntax :
           numpy.identity(n, dtype=None)


In [23]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**ndim**

1. np.ndim is a NumPy function that returns the number of dimensions (axes) of an array.

Syntax : numpy.ndim(a)


In [25]:
dimi = np.arange(12,dtype=float).reshape(3,4)
print(dimi)
print(dimi.ndim)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
2


# **Shape:**

1. In NumPy, shape refers to the dimensions of an array — essentially the number of elements along each axis.

2. Syntax: array.shape


In [26]:
print(dimi.shape)

(3, 4)


# **Size :**

* In NumPy, size gives the total number of elements in an array, regardless of its shape or dimensions.
* Syntax: array.size


In [27]:
print(dimi.size)   # Shape (3,4) --> 3 * 4 = 12

12


**# Functions**


In [35]:
a = np.random.random((3,3))
a = np.round(a * 100)

print(a)

[[ 1. 71. 31.]
 [81. 21.  5.]
 [73. 80. 75.]]


# Max :

In [43]:
import numpy as np

b = np.arange(12).reshape(3,4)
print(b)

print('---------------------------------------------------------')
# Find the max value in each row (axis=1 → row-wise)
print(f'max value row-wise {np.max(b, axis=1)}')

print('---------------------------------------------------------')
# Find the max value in each column (axis=0 → column-wise)
print(f'max value column-wise {np.max(b, axis=0)}')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------------------------------------------------
max value row-wise [ 3  7 11]
---------------------------------------------------------
max value column-wise [ 8  9 10 11]


# min value row & column wise

In [44]:
import numpy as np

b = np.arange(12).reshape(3,4)
print(b)

print('---------------------------------------------------------')
# Find the min value in each row (axis=1 → row-wise)
print(f'min value row-wise {np.min(b, axis=1)}')

print('---------------------------------------------------------')
# Find the min value in each column (axis=0 → column-wise)
print(f'min value column-wise {np.min(b, axis=0)}')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------------------------------------------------
min value row-wise [0 4 8]
---------------------------------------------------------
min value column-wise [0 1 2 3]


# **Sum / Prod Function**

**axis=0 → operate down columns.

axis=1 → operate across rows.**

In [52]:
a = np.arange(12).reshape(3,4)


print(a)
print('-------------------------------------------------------------')
print(f'Total matrix sum  value : {np.sum(a)}')
print('-------------------------------------------------------------')
print(f'Total sum row-wise {np.sum(a, axis=1)}')
print('-------------------------------------------------------------')
print(f'Total sum column-wise {np.sum(a, axis=0)}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------------
Total matrix sum  value : 66
-------------------------------------------------------------
Total sum row-wise [ 6 22 38]
-------------------------------------------------------------
Total sum column-wise [12 15 18 21]


prod :

In [53]:
a = np.arange(12).reshape(3,4)


print(a)
print('-------------------------------------------------------------')
print(f'Total matrix prod  value : {np.prod(a)}')
print('-------------------------------------------------------------')
print(f'Total prod row-wise {np.prod(a, axis=1)}')
print('-------------------------------------------------------------')
print(f'Total prod column-wise {np.prod(a, axis=0)}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------------
Total matrix prod  value : 0
-------------------------------------------------------------
Total prod row-wise [   0  840 7920]
-------------------------------------------------------------
Total prod column-wise [  0  45 120 231]


# mean/median/srd/var

In [54]:
import numpy as np

a = np.arange(12).reshape(3,4)

print(a)
print('-------------------------------------------------------------')
print(f'Total matrix mean value : {np.mean(a)}')
print('-------------------------------------------------------------')
print(f'Total mean row-wise {np.mean(a, axis=1)}')
print('-------------------------------------------------------------')
print(f'Total mean column-wise {np.mean(a, axis=0)}')
print('-------------------------------------------------------------')
print(f'Total matrix median value : {np.median(a)}')
print('-------------------------------------------------------------')
print(f'Total median row-wise {np.median(a, axis=1)}')
print('-------------------------------------------------------------')
print(f'Total median column-wise {np.median(a, axis=0)}')
print('-------------------------------------------------------------')
print(f'Total matrix standard deviation : {np.std(a)}')
print('-------------------------------------------------------------')
print(f'Total std row-wise {np.std(a, axis=1)}')
print('-------------------------------------------------------------')
print(f'Total std column-wise {np.std(a, axis=0)}')
print('-------------------------------------------------------------')
print(f'Total matrix variance : {np.var(a)}')
print('-------------------------------------------------------------')
print(f'Total var row-wise {np.var(a, axis=1)}')
print('-------------------------------------------------------------')
print(f'Total var column-wise {np.var(a, axis=0)}')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------------
Total matrix mean value : 5.5
-------------------------------------------------------------
Total mean row-wise [1.5 5.5 9.5]
-------------------------------------------------------------
Total mean column-wise [4. 5. 6. 7.]
-------------------------------------------------------------
Total matrix median value : 5.5
-------------------------------------------------------------
Total median row-wise [1.5 5.5 9.5]
-------------------------------------------------------------
Total median column-wise [4. 5. 6. 7.]
-------------------------------------------------------------
Total matrix standard deviation : 3.452052529534663
-------------------------------------------------------------
Total std row-wise [1.11803399 1.11803399 1.11803399]
-------------------------------------------------------------
Total std column-wise [3.26598632 3.26598632 3.26598632 3.26598632]
--------------

# Indexing

In [90]:
a1 = np.arange(10)
print(a1)

print('-----------------------------------------------------')
a2 = np.arange(12).reshape(4,3)

print(a2)

print('-----------------------------------------------------')
a3 = np.arange(30).reshape(3,5,2)  # now includes 0..29
print(a3)



[0 1 2 3 4 5 6 7 8 9]
-----------------------------------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-----------------------------------------------------
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [65]:
print(a1[0])

0


In [74]:
# 2D array

print(a2)
print('-----------------------------------------------------')

print(a2[1])
print('-----------------------------------------------------')

print(a2[3,2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-----------------------------------------------------
[3 4 5]
11


**# 3D**  ARRAY


In [91]:
print(a3)

print('-----------------------------------------------------')

print(a3[2,2])

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
-----------------------------------------------------
[24 25]


**# Slicing**

In [92]:
#1D Array
print(a1)
print(a1[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [93]:
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [99]:
#Fetch [4,5,7,8]

print(a2[1:3,1:3])

[[4 5]
 [7 8]]


In [113]:
#Fetcch the [1,2,10,11]

print(a2[::3,1:])

[[ 1  2]
 [10 11]]


In [145]:
#Fetch the [3,4,9,10]

print(a2[[1,3], :2])

[[ 3  4]
 [ 9 10]]


In [150]:
#Horzontally

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)


print(np.hstack((a4,a5)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [151]:
#Vertical stacking


print(np.vstack((a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [153]:
a6 = np.vstack([a4,a5])

print(np.hsplit(a6,2))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]


In [155]:
print(np.vsplit(a6,3))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]
